In [404]:
import pandas as pd
import numpy as np
import matplotlib as mpl

In [405]:
df = pd.DataFrame([[38.0, 2.0, 18.0, 22.0, 21, np.nan],[19, 439, 6, 452, 226,232]],
                  index=pd.Index([
                      'Tumour (Positive)', 
                      'Non-Tumour (Negative)'], name='Actual Label:'),
                  columns=pd.MultiIndex.from_product([[
                      'Decision Tree', 'Regression', 'Random'],
                      ['Tumour', 'Non-Tumour']], names=['Model:', 'Predicted:']))
df.style

In [406]:
s = df.style.format('{:.0f}').hide([('Random', 'Tumour'), ('Random', 'Non-Tumour')], axis="columns")

cell_hover = {
    'selector': 'td:hover',
    'props': [('background-color', "#ffffb3")]
}
index_names= {
    'selector': '.index_name',
    'props': 'font-style: italic; color: darkgrey; font-weight: normal;'
}
headers = {
    'selector': 'th:not(.index_name)',
    'props': 'background-color: #000066; color: white;'
}
s.set_table_styles([cell_hover, index_names, headers])

In [407]:
s.set_table_styles([
    {'selector': 'th.col_heading', 'props': 'text-align: center;'},
    {'selector': 'th.col_heading.level0', 'props': 'font-size: 1.5em;'},
    {'selector': 'td', 'props': 'text-align: center; font-weight: bold;'},    
], overwrite=False)

In [408]:
np.random.seed(0)
df2 = pd.DataFrame(np.random.randn(10,4), columns=['A','B','C','D'])
df2.style

In [409]:
df3 = pd.DataFrame(np.random.randn(4,4),
                   pd.MultiIndex.from_product([['A', 'B'], ['r1', 'r2']]),
                   columns=['c1','c2','c3','c4'])
df3

            c1        c2        c3        c4
A r1 -1.048553 -1.420018 -1.706270  1.950775
  r2 -0.509652 -0.438074 -1.252795  0.777490
B r1 -1.613898 -0.212740 -0.895467  0.386902
  r2 -0.510805 -1.180632 -0.028182  0.428332

In [410]:
idx = pd.IndexSlice
slice_ = idx[idx[:,'r2'], idx[:'c4']]
df3.style.set_properties(**{'background-color': '#ffffb3'}, subset=slice_)